ERP_FINAL/Controllers/ReporteController.cs
using Entidad;
using Entidad.EReportes;
using Entidad.Enums;
using Logica;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;

namespace ERP_FINAL.Controllers
{
    public class ReporteController : Controller
    {
        private LGestion lLogicagestion = LGestion.Instancia.LGestion;
        private LEmpresaMoneda lLogicaEmpresamoneda = LEmpresaMoneda.Instancia.LEmpresaMoneda;
        private LComprobante lLogicacomprobante = LComprobante.Instancia.LComprobante;
        private LReporte lLogicareporte = LReporte.Instancia.LReporte;
        private LPeriodo lLogicaperiodo = LPeriodo.Instancia.LPeriodo;
        private LBalanceInicial lLogicabalanceinicial = LBalanceInicial.Instancia.LBalanceInicial;
        private LEstadoResultados llogicaestadoresultado = LEstadoResultados.Instancia.LEstadoResultados;
        private LRBalanceGeneral llogicabalancegeneral = LRBalanceGeneral.Instancia.LRBalanceGeneral;
        // GET: Reporte
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ReporteComprobacionSumasySaldos()
        {
            try
            {
                EUsuario sUsuario = (EUsuario)Session["Usuario"];
                EEmpresa sEmpresa = (EEmpresa)Session["Empresa"];

                ViewBag.Gestion = lLogicagestion.ObtenerPorIdEmpresa(sEmpresa.Id);
                ViewBag.EmpresaMonedas = lLogicacomprobante.ObtenerMonedasComprobante(sEmpresa.Id, sUsuario.Id);

                return View();

            }
            catch (BussinessException ex)
            {
                string mensaje = ex.Message.Replace("'", "");
                ViewBag.Mensaje = mensaje;
                return JavaScript("MostrarMensaje('" + mensaje + "');");
            }
            catch (Exception ex)
            {
                return JavaScript("MostrarMensaje('Ha ocurrido un error');");
            }
        }

        public ActionResult ReporteDeSumasySaldos(int idgestion, int idmoneda)
        {
            try
            {
                EUsuario sUsuario = (EUsuario)Session["Usuario"];
                EEmpresa sEmpresa = (EEmpresa)Session["Empresa"];
                EGestion gestion = new EGestion();
                EMoneda moneda = new EMoneda();
                gestion = lLogicagestion.ObtenerPorid(idgestion);                             
                moneda = lLogicaEmpresamoneda.ObtenerMonedaPorId(idmoneda);

                List<ERDatosBasicoSumasSaldos> datosBasico = new List<ERDatosBasicoSumasSaldos>();
                datosBasico = lLogicareporte.ReporteDatosBasicos(sUsuario.Nombre, sEmpresa.Nombre, gestion.Nombre, moneda.Nombre);

                List<ERSumasSaldos> detalleComprobantes = new List<ERSumasSaldos>();
                detalleComprobantes = lLogicareporte.ReporteDeSumasySaldos(idgestion, idmoneda);     

                ReportViewer viewer = new ReportViewer();
                viewer.AsyncRendering = false;
                viewer.SizeToReportContent = true;

                ReportDataSource rb = new ReportDataSource("DSReporteDatosBasico", datosBasico);
                ReportDataSource rcdetalle = new ReportDataSource("DSReporteSumasSaldos", detalleComprobantes);               

                viewer.LocalReport.ReportPath = Server.MapPath("~/Reportes/ReporteSumasSaldos.rdlc");
                viewer.LocalReport.DataSources.Clear();

                viewer.LocalReport.DataSources.Add(rb);
                viewer.LocalReport.DataSources.Add(rcdetalle);               

                viewer.LocalReport.Refresh();

                ViewBag.ReporteSaldosSumas = viewer;


                return PartialView("ReporteSumasySaldosParcial");
            }
            catch (BussinessException ex)
            {
                string mensaje = ex.Message.Replace("'", "");
                ViewBag.Mensaje = mensaje;
                return JavaScript("MostrarMensaje('" + mensaje + "');");
            }
            catch (Exception ex)
            {
                return JavaScript("MostrarMensaje('Ha ocurrido un error');");
            }
        }

        public ActionResult ReporteBalanceInicial()
        {
            try
            {
                EUsuario sUsuario = (EUsuario)Session["Usuario"];
                EEmpresa sEmpresa = (EEmpresa)Session["Empresa"];

                ViewBag.Gestion = lLogicagestion.ObtenerPorIdEmpresa(sEmpresa.Id);
                ViewBag.EmpresaMonedas = lLogicacomprobante.ObtenerMonedasComprobante(sEmpresa.Id, sUsuario.Id);

                return View();

            }
            catch (BussinessException ex)
            {
                string mensaje = ex.Message.Replace("'", "");
                ViewBag.Mensaje = mensaje;
                return JavaScript("MostrarMensaje('" + mensaje + "');");
            }
            catch (Exception ex)
            {
                return JavaScript("MostrarMensaje('Ha ocurrido un error');");
            }
        }

        public ActionResult ReporteDeBalanceInicial(int idgestion, int idmoneda)
        {
            try
            {
                EUsuario sUsuario = (EUsuario)Session["Usuario"];
                EEmpresa sEmpresa = (EEmpresa)Session["Empresa"];
                EGestion gestion = new EGestion();
                EMoneda moneda = new EMoneda();
                gestion = lLogicagestion.ObtenerPorid(idgestion);
                var fechagestion = "Del " + gestion.fechaIni + " Al " + gestion.fechaFi;
                moneda = lLogicaEmpresamoneda.ObtenerMonedaPorId(idmoneda);              

                if (sEmpresa.Niveles == 3)
                {
                    List<ERDatosBasicoBalanceInicial> datosBasico = new List<ERDatosBasicoBalanceInicial>();
                    datosBasico = lLogicabalanceinicial.ReporteDatosBasicosBalanceInicial(sUsuario.Nombre, sEmpresa.Nombre, gestion.Nombre, fechagestion, moneda.Nombre);

                    List<ERCabeceraActivo> cabeceraactivo = new List<ERCabeceraActivo>();
                    cabeceraactivo = lLogicabalanceinicial.cabeceraactivos(idgestion, sEmpresa.Id, idmoneda);

                    List<ERCabeceraPasivoPatrimonio> cabecerapasivopatrimonio = new List<ERCabeceraPasivoPatrimonio>();
                    cabecerapasivopatrimonio = lLogicabalanceinicial.cabecerapasivopatrimonios(idgestion, sEmpresa.Id, idmoneda);

                    List<ERBalanceInicialActivo> detallecomprobantesactivo = new List<ERBalanceInicialActivo>();
                    detallecomprobantesactivo = lLogicabalanceinicial.reporteBalanceInicialActivo(idgestion, sEmpresa.Id, idmoneda);

                    List<ERBalanceInicialPasivoPatrimonio> detallecomprobantepasivopatrimonio = new List<ERBalanceInicialPasivoPatrimonio>();
                    detallecomprobantepasivopatrimonio = lLogicabalanceinicial.reporteBalanceInicialPasivoPatrimonio(idgestion, sEmpresa.Id, idmoneda);          

                    ReportViewer viewer = new ReportViewer();
                    viewer.AsyncRendering = false;
                    viewer.SizeToReportContent = true;

                    ReportDataSource rb = new ReportDataSource("DSReporteDatosBasico", datosBasico);
                    ReportDataSource rcdetalleactivo = new ReportDataSource("DSReporteBalanceInicialActivo", detallecomprobantesactivo);
                    ReportDataSource rcdetallepasivopatrimonio = new ReportDataSource("DSReporteBalanceInicialPasivoPatrimonio", detallecomprobantepasivopatrimonio);
                    ReportDataSource rccabeceraactivo = new ReportDataSource("DSCabecera1", cabeceraactivo);
                    ReportDataSource rccabecerapasivopatrimonio = new ReportDataSource("DSCabecera2", cabecerapasivopatrimonio);

                    viewer.LocalReport.ReportPath = Server.MapPath("~/Reportes/ReporteBalanceInicial.rdlc");
                    viewer.LocalReport.DataSources.Clear();
                    viewer.LocalReport.DataSources.Add(rb);
                    viewer.LocalReport.DataSources.Add(rcdetalleactivo);
                    viewer.LocalReport.DataSources.Add(rcdetallepasivopatrimonio);
                    viewer.LocalReport.DataSources.Add(rccabeceraactivo);
                    viewer.LocalReport.DataSources.Add(rccabecerapasivopatrimonio);
                    viewer.LocalReport.Refresh();

                    ViewBag.ReporteBalanceInicial = viewer;
                }
                else if (sEmpresa.Niveles == 4)
                {
                    List<ERDatosBasicoBalanceInicial> datosBasico = new List<ERDatosBasicoBalanceInicial>();
                    datosBasico = lLogicabalanceinicial.ReporteDatosBasicosBalanceInicial(sUsuario.Nombre, sEmpresa.Nombre, gestion.Nombre, fechagestion, moneda.Nombre);

                    List<ERCabeceraActivo> cabeceraactivo = new List<ERCabeceraActivo>();
                    cabeceraactivo = lLogicabalanceinicial.cabeceraactivos(idgestion, sEmpresa.Id, idmoneda);

                    List<ERCabeceraPasivoPatrimonio> cabecerapasivopatrimonio = new List<ERCabeceraPasivoPatrimonio>();
                    cabecerapasivopatrimonio = lLogicabalanceinicial.cabecerapasivopatrimonios(idgestion, sEmpresa.Id, idmoneda);

                    List<ERBalanceInicialActivo> detallecomprobantesactivo = new List<ERBalanceInicialActivo>();
                    detallecomprobantesactivo = lLogicabalanceinicial.reporteBalanceInicialActivo(idgestion, sEmpresa.Id, idmoneda);

                    List<ERBalanceInicialPasivoPatrimonio> detallecomprobantepasivopatrimonio = new List<ERBalanceInicialPasivoPatrimonio>();
                    detallecomprobantepasivopatrimonio = lLogicabalanceinicial.reporteBalanceInicialPasivoPatrimonio(idgestion, sEmpresa.Id, idmoneda);

                    ReportViewer viewer = new ReportViewer();
                    viewer.AsyncRendering = false;
                    viewer.SizeToReportContent = true;

ERP_FINAL/Views/Reporte/ReporteBalanceGeneral.cshtml
@using ReportViewerForMvc;
@using Entidad;
@{
    ViewBag.Title = "ReporteBalanceGeneral";
    List<EGestion> gestiones = ViewBag.Gestion;
    List<EMoneda> empresaMonedas = ViewBag.EmpresaMonedas; }

@section EtiquetaHead
    {
    <link href="@Url.Content("~/Content/adminLte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-datepicker/css/bootstrap-datepicker.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-datepicker/css/bootstrap-datepicker3.css")" rel="stylesheet" />
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Reporte Balance General</h3>
                    </div>
                    <div class="card-body">
                        <div class="row ">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Gestion</label>
                                    <select class="form-control select2" style="width: 100%;" id="select_gestion">
                                        @{ 
                                            foreach (var i in gestiones)
                                            {
                                                <option value="@i.Id">@i.Nombre</option> 
                                            }
                                          }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Moneda</label>
                                    <select class="form-control select2" style="width: 100%;" id="select_moneda">
                                        @{ 
                                            foreach (var i in empresaMonedas)
                                            {
                                                <option value="@i.Id">@i.Abreviatura - @i.Nombre</option> 
                                             } 
                                         }
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <button class="btn btn-primary" onclick="GenerarReporte()" style="margin-top: 30px;"> <i class="fas fa-print"></i> Generar Reporte </button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="contenedor" style="width:1000px; height:900px; ">
                            @Html.Partial("ReporteBalanceGeneralParcial")
                        </div>
                    </div>

                    <div class="card-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{

    <script src="@Url.Content("~/Content/adminLte/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/js/dataTables.responsive.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/Content/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>

    <script type="text/javascript">
        $(document).ready(function () {

        });

        function GenerarReporte()
        {
            var IdGestion = $("#select_gestion").val();
            var IdMoneda = $("#select_moneda").val();

            $.ajax({
                url: "@Url.Action("ReporteDeBalanceGeneral", "Reporte")",
                cache: false,
                data: {
                    idgestion: IdGestion,
                    idmoneda: IdMoneda
                },
                type: "GET", success: function (html) {
                    $("#contenedor").html(html);
                }
            })
        }

        function redireccionar(url) {
            window.location = url;
        }

        function MostrarMensaje(msj) {
            $(document).Toasts('create', {
                class: ' bg-danger',
                title: "Alerta",
                autohide: true,
                delay: 10000,
                body: msj
            });
        }
    </script>

}

ERP_FINAL/Views/Reporte/ReporteBalanceGeneralParcial.cshtml
@using ReportViewerForMvc;
@using Entidad;

@{ 
    if (ViewBag.ReporteBalanceGeneral != null)
    {
        @Html.ReportViewer(ViewBag.ReporteBalanceGeneral as Microsoft.Reporting.WebForms.ReportViewer, new { style = "width: 900px; height:900px;" }) 
    } 
}

ERP_FINAL/Views/Reporte/ReporteBalanceInicial.cshtml
@using ReportViewerForMvc;
@using Entidad;
@{ 
    ViewBag.Title = "ReporteBalanceInicial";
    List<EGestion> gestiones = ViewBag.Gestion;
    List<EMoneda> empresaMonedas = ViewBag.EmpresaMonedas; 
}

@section EtiquetaHead
    {
    <link href="@Url.Content("~/Content/adminLte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-datepicker/css/bootstrap-datepicker.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-datepicker/css/bootstrap-datepicker3.css")" rel="stylesheet" />
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Reporte Balance Inicial</h3>
                    </div>
                    <div class="card-body">
                        <div class="row ">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Gestion</label>
                                    <select class="form-control select2" style="width: 100%;" id="select_gestion">
                                        @{ 
                                            foreach (var i in gestiones)
                                            {
                                                <option value="@i.Id">@i.Nombre</option>
                                            } 
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Moneda</label>
                                    <select class="form-control select2" style="width: 100%;" id="select_moneda">
                                        @{ 
                                            foreach (var i in empresaMonedas)
                                            {
                                                <option value="@i.Id">@i.Abreviatura - @i.Nombre</option>
                                            } 
                                        }
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <button class="btn btn-primary" onclick="GenerarReporte()" style="margin-top: 30px;"> <i class="fas fa-print"></i> Generar Reporte </button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="contenedor" style="width:1000px; height:900px; ">
                            @Html.Partial("ReporteBalanceInicialParcial")
                        </div>
                    </div>

                    <div class="card-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{

    <script src="@Url.Content("~/Content/adminLte/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/js/dataTables.responsive.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/Content/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>

    <script type="text/javascript">
        $(document).ready(function () {

        });

        function GenerarReporte()
        {
            var IdGestion = $("#select_gestion").val();
            var IdMoneda = $("#select_moneda").val();

            $.ajax({
                url: "@Url.Action("ReporteDeBalanceInicial", "Reporte")",
                cache: false,
                data: {
                    idGestion: IdGestion,
                    idMoneda: IdMoneda
                },
                type: "GET", success: function (html) {
                    $("#contenedor").html(html);
                }
            })
        }

        function redireccionar(url) {
            window.location = url;
        }

        function MostrarMensaje(msj) {
            $(document).Toasts('create', {
                class: ' bg-danger',
                title: "Alerta",
                autohide: true,
                delay: 10000,
                body: msj
            });
        }
    </script>

}

ERP_FINAL/Views/Reporte/ReporteBalanceInicialParcial.cshtml
@using ReportViewerForMvc;
@using Entidad;

@{ 
    if (ViewBag.ReporteBalanceInicial != null)
    {
        @Html.ReportViewer(ViewBag.ReporteBalanceInicial as Microsoft.Reporting.WebForms.ReportViewer, new { style = "width: 900px; height:900px;" }) 
    } 
}

ERP_FINAL/Views/Reporte/ReporteComprobacionSumasySaldos.cshtml
@using ReportViewerForMvc;
@using Entidad;
@{ 
    ViewBag.Title = "ReporteComprobacionSumasySaldos";
    List<EGestion> gestiones = ViewBag.Gestion;
    List<EMoneda> empresaMonedas = ViewBag.EmpresaMonedas; 
}

@section EtiquetaHead
    {
    <link href="@Url.Content("~/Content/adminLte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-datepicker/css/bootstrap-datepicker.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-datepicker/css/bootstrap-datepicker3.css")" rel="stylesheet" />
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Reporte Comprobacion de Sumas y Saldos</h3>
                    </div>
                    <div class="card-body">
                        <div class="row ">                           
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Gestion</label>
                                    <select class="form-control select2" style="width: 100%;" id="select_gestion">
                                        @{ 
                                            foreach (var i in gestiones)
                                            {
                                                <option value="@i.Id">@i.Nombre</option> } 
                                            }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Moneda</label>
                                    <select class="form-control select2" style="width: 100%;" id="select_moneda">
                                        @{ 
                                            foreach (var i in empresaMonedas)
                                            {
                                                <option value="@i.Id">@i.Abreviatura - @i.Nombre</option>                                               
                                            } 
                                        }
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <button class="btn btn-primary" onclick="GenerarReporte()" style="margin-top: 30px;"> <i class="fas fa-print"></i> Generar Reporte </button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="contenedor" style="width:1000px; height:900px; ">
                            @Html.Partial("ReporteSumasySaldosParcial")
                        </div>
                    </div>
                    
                    <div class="card-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{

    <script src="@Url.Content("~/Content/adminLte/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/js/dataTables.responsive.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/Content/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>

    <script type="text/javascript">
        $(document).ready(function () {

        });

        function GenerarReporte()
        {
            var IdGestion = $("#select_gestion").val();           
            var IdMoneda = $("#select_moneda").val();            

            $.ajax({
                url: "@Url.Action("ReporteDeSumasySaldos", "Reporte")",
                cache: false,
                data: {
                    idGestion: IdGestion,
                    idMoneda: IdMoneda
                },
                type: "GET", success: function (html) {
                    $("#contenedor").html(html);
                }
            })
        }

        function redireccionar(url) {
            window.location = url;
        }

        function MostrarMensaje(msj) {
            $(document).Toasts('create', {
                class: ' bg-danger',
                title: "Alerta",
                autohide: true,
                delay: 10000,
                body: msj
            });
        }
    </script>

}

ERP_FINAL/Views/Reporte/ReporteEstadoResultado.cshtml
@using ReportViewerForMvc;
@using Entidad;
@{
    ViewBag.Title = "ReporteEstadoResultado";
    List<EGestion> gestiones = ViewBag.Gestion;
    List<EMoneda> empresaMonedas = ViewBag.EmpresaMonedas; }

@section EtiquetaHead
    {
    <link href="@Url.Content("~/Content/adminLte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-datepicker/css/bootstrap-datepicker.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-datepicker/css/bootstrap-datepicker3.css")" rel="stylesheet" />
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Reporte Estado de Resultados</h3>
                    </div>
                    <div class="card-body">
                        <div class="row ">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Gestion</label>
                                    <select class="form-control select2" style="width: 100%;" id="select_gestion">
                                        @{
                                            foreach (var i in gestiones)
                                            {
                                                <option value="@i.Id">@i.Nombre</option>

                                            }
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Moneda</label>
                                    <select class="form-control select2" style="width: 100%;" id="select_moneda">
                                        @{
                                            foreach (var i in empresaMonedas)
                                            {
                                                <option value="@i.Id">@i.Abreviatura - @i.Nombre</option>

                                            }
                                        }
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <button class="btn btn-primary" onclick="GenerarReporte()" style="margin-top: 30px;"> <i class="fas fa-print"></i> Generar Reporte </button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="contenedor" style="width:1000px; height:900px; ">
                            @Html.Partial("ReporteEstadoResultadoParcial")
                        </div>
                    </div>

                    <div class="card-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{

    <script src="@Url.Content("~/Content/adminLte/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/js/dataTables.responsive.min.js")"></script>
    <script src="@Url.Content("~/Content/adminLte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/Content/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>

    <script type="text/javascript">
        $(document).ready(function () {

        });

        function GenerarReporte()
        {
            var IdGestion = $("#select_gestion").val();
            var IdMoneda = $("#select_moneda").val();

            $.ajax({
                url: "@Url.Action("ReporteDeEstadoResultados", "Reporte")",
                cache: false,
                data: {
                    idgestion: IdGestion,
                    idmoneda: IdMoneda
                },
                type: "GET", success: function (html) {
                    $("#contenedor").html(html);
                }
            })
        }

        function redireccionar(url) {
            window.location = url;
        }

        function MostrarMensaje(msj) {
            $(document).Toasts('create', {
                class: ' bg-danger',
                title: "Alerta",
                autohide: true,
                delay: 10000,
                body: msj
            });
        }
    </script>

}